### ISSUE TITLE
Missing logo in docs

### ISSUE THREAD

**Issue by kmichael08** [Yu-Group/veridical-flow#10]
Both in Firefox 92.0 and Chromium 92.0

![Screenshot 2021-11-21 at 15-26-26 vflow API documentation](https://user-images.githubusercontent.com/15304831/142765857-b27e758f-9f73-45a1-a7a8-bfb797aa8c7e.png)

**Comment by jbytecode** [comment]
I am leaving a link here so we can track the issue in JOSS review thread:

This issue is due to https://github.com/openjournals/joss-reviews/issues/3895

**Comment by csinva** [comment]
Thanks for catching this! Just fixed it.
