### ISSUE TITLE
Test xfails

### ISSUE THREAD

**Issue by kmichael08** [Yu-Group/veridical-flow#11]
As far as I understand xfail tests, it is supposed to be a temporary flag rather than a test for a failing case.
Could you explain why are you using it here?

https://github.com/Yu-Group/veridical-flow/blob/cfa83c14a7cc2673f9db8acd593072c9c321b609/tests/test_convert.py#L465

**Comment by jbytecode** [comment]
@kmichael08 thank you for effort on reviewing.

Could you please mention the JOSS thread here, so we can keep tracking of your work.

Thank you in advance.

Due to JOSS submission: https://github.com/openjournals/joss-reviews/issues/3895

**Comment by aagarwal1996** [comment]
closed by #21 

Issue no longer applies.
