### ISSUE TITLE
Tests – warnings and code coverage

### ISSUE THREAD

**Issue by kmichael08** [Yu-Group/veridical-flow#12]
I get 5 warnings when running tests:
[tests.txt](https://github.com/Yu-Group/veridical-flow/files/7576566/tests.txt

Also, the code coverage is 69%, perhaps it could be a bit better:
![Screenshot 2021-11-21 at 16-38-31 Coverage report](https://user-images.githubusercontent.com/15304831/142769114-e19c17e3-1ef4-47b2-8b03-1f95894c65ea.png)
)

Feel free to close this issue, just pointing out things that could be improved but perhaps don't need to.

**Comment by jbytecode** [comment]
https://github.com/openjournals/joss-reviews/issues/3895

**Comment by rushk014** [comment]
Code coverage is improved by 5e92bc4fe626de387c68c93ace8cd20add813c06
<img width="655" alt="Screen Shot 2021-12-10 at 1 49 44 PM" src="https://user-images.githubusercontent.com/29556139/145645621-29bf6a11-6519-41de-9a53-eac834d63b2e.png">

**Comment by kmichael08** [comment]
Well, I'm not sure it's an upgrade in percentage terms. Above you include the test files to the 75% coverage, which I excluded. The number of missing lines is up. Anyways, I've seen you added a new test case which is good!
