### ISSUE TITLE
Default argument equals [], {}

### ISSUE THREAD

**Issue by kmichael08** [Yu-Group/veridical-flow#13]
I believe it is generally discouraged to use `[]` and perhaps similarly `{}` as a default function argument:
https://github.com/Yu-Group/veridical-flow/blob/cfa83c14a7cc2673f9db8acd593072c9c321b609/vflow/convert.py#L122

See https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument.
One idea is to set the default to `None`.
This happens several times in this repository, so if you decide to change it, please search for all occurences

**Comment by jbytecode** [comment]
@kmichael08 thank you for your effort on reviewing.

Could you please mention the JOSS thread here, so we can keep tracking of your work.

Thank you in advance.

Due to JOSS submission: https://github.com/openjournals/joss-reviews/issues/3895

**Comment by csinva** [comment]
fixed!
