### ISSUE TITLE
Notebook example – no data given in the link

### ISSUE THREAD

**Issue by kmichael08** [Yu-Group/veridical-flow#14]
I run the examples, and the example below uses the data not uploaded to the repo.

https://github.com/Yu-Group/veridical-flow/blob/cfa83c14a7cc2673f9db8acd593072c9c321b609/notebooks/01_enhancer.ipynb?short_path=14469c6#L69

Due to JOSS submission:  https://github.com/openjournals/joss-reviews/issues/3895

**Comment by rushk014** [comment]
fixed by 439263742a3e68444c6948c74e8576167e26e16d

**Comment by kmichael08** [comment]
Got `FileNotFoundError: [Errno 2] No such file or directory: '../data/fit_feat.txt'` in notebook _02_fmri_

**Comment by kmichael08** [comment]
Notebook `00_mlflow_tracking.ipynb` prints an error on the output uploaded to GH

**Comment by kmichael08** [comment]
`%% time` notebook magic doesn't work for me. I needed to remove the space. But maybe it's jupyter version-dependent?
I'm referring to the Ray example.
