### ISSUE TITLE
Redundant requirement

### ISSUE THREAD

**Issue by kmichael08** [Yu-Group/veridical-flow#18]
It seems you're not using sklearn anywhere in the package.
If that's the case and it is used for examples, perhaps you could create a separate requirements set and keep the original as slim as possible.

https://github.com/Yu-Group/veridical-flow/blob/cfa83c14a7cc2673f9db8acd593072c9c321b609/setup.py#L26
Due to JOSS submission: openjournals/joss-reviews#3895

**Comment by csinva** [comment]
Thanks for pointing this out! We've moved it into the optional "dev" requirements in the [setup.py](https://github.com/Yu-Group/veridical-flow/blob/master/setup.py) file. (So it would be installed used `pip install .[dev]` rather than the standard `pip install .`).
